panoptes/webapp/users/views.py
# system imports
import datetime
# framework imports
from flask import Blueprint, request, render_template, flash, redirect, url_for, session, current_app, jsonify
from flask.ext.login import login_user, logout_user, login_required, current_user
# app imports
from models import Users
from forms import UserForm, LoginForm, ResetPassForm, NewPassForm, ChangePassForm
from ..utils.mail import send_email


mod = Blueprint('users',__name__)


@mod.before_request
def before_request():
    session['menu'] = current_app.config['MENU']
    session['activemenu'] = 'utilizatori'


@mod.route('/login', methods=['GET','POST'])
def login():
    """
    Generates and handles the login for the user
    """
    form = LoginForm()

    if form.validate_on_submit():
        try:
            user = Users.get({"email":form.email.data})
            if not user.active.value:
                flash('Contul tau a expirat! Te rugam contacteaza-ne!', category='alert-danger')
                return redirect(request.referrer)
            if user.verify_password(form.password.data):
                login_user(user,form.remember_me.data)
                user.ping()
                return redirect('/')
            else:
                raise Exception('Not authorised',form.email.data)

        except Exception as err:
            print err
            flash('Parola sau adresa de email este invalida!', category='alert-danger')

    return render_template('users/login.html', pagetitle='Login',form=form,login=True, current_user=current_user)


@mod.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect('/')


@mod.route('/reseteazaparola/', methods=['GET','POST'])
def resetlink():
    """
    Generates and handles the password reset page
    """

    form = ResetPassForm()

    if form.validate_on_submit():
        try:
            user = Users.get({"email":form.email.data})
            token = user.generate_reset_token()
            send_email(user.email,'Resetare parola','users/email/passwdreset',user=user,token=token)
            flash('Parola a fost resetata! Va rugam urmati instructiunile primite pe email!',category='alert-success')
            return redirect(request.referrer)

        except Exception as err:
            flash('Adresa de email gresita!',category='alert-danger')
            return redirect(request.referrer)

    return render_template('users/login.html',pagetitle='Resetare parola',form=form,login=False)


@mod.route('/reseteaza/<email>/<token>', methods=['GET','POST'])
def resetpassword(email,token):
    """
    Handles the password reset for a given email and token
    """

    form = NewPassForm()

    if form.validate_on_submit():
        try:
            user = Users.get({"email":email})
            if user.resetpass(token):
                user.password = form.password.data
                user.save()
                flash('Parola schimbata!',category='alert-success')
                return redirect(url_for('users.login'))
                
            else:
                raise Exception

        except:
            flash('Token invalid!',category='alert-danger')
            return redirect(url_for('users.resetlink'))

    return render_template('users/login.html',pagetitle='Resetare parola',form=form,login=False)


@mod.route('/schimbaparola', methods=['GET','POST'])
@login_required
def changepswd():
    """
    Handles the change of password for the current user
    """

    form = ChangePassForm()

    if form.validate_on_submit():
        try:
            user = current_user
            print "here"
            if user.verify_password(form.oldpass.data):
                print "pass ok"
                user.password = form.newpass.data
                print user.username.value
                print form.newpass.data
                user.save()
                flash('Parola schimbata!',category='alert-success')
                return redirect(request.args.get('next') or '/home/')
            else:
                raise Exception('Not authorised',form.email.data)

        except Exception as err:
            print err
            flash('Modificarea nu poate fi facuta!', category='alert-danger')

    return render_template('users/edit.html', pagetitle='Schimba parola', form=form)


@mod.route('/home')
@login_required
def home():
    """
    Generates the homepage for the logged in user
    """

    return redirect(url_for('users.list_users'))


@mod.route('/utilizatori/lista')
@login_required
def list_users():
    """
    Generates a list of all users
    """
    return render_template('users/list.html', pagetitle='Lista Utilizatori', results=url_for('users.get_results'), table_head=Users.table_head(), columns=Users.datatables_columns())


@mod.route('/utilizatori/adauga', methods=['GET','POST'])
@login_required
def add_user():
    """
    Used to add a new user to the admin
    """

    form = UserForm()

    if form.validate_on_submit():
        try:
            user = Users()
            user.populate_from_form(form)
            send_email(user.email.value,'Resetare parola','users/email/sendpass',user=user,psw=user.random_password())
            user.save()
            flash('Utilizatorul adaugat!', category='alert-success')
            return redirect(url_for('users.list_users'))
        except Exception as err:
            flash('Utilizatorul nu poate fi adaugat!', category='alert-danger')

    return render_template('users/add.html', pagetitle='Adauga utilizator', form=form)


@mod.route('/utilizatori/modifica/<userid>', methods=['GET','POST'])
@login_required
def edit_user(userid):
    """
    Used to edit an existing user
    """
    
    user = Users.get({"_id":userid})
    form = UserForm()

    if form.validate_on_submit():
        try:
            user.populate_from_form(form)
            user.save()
            flash('Utilizatorul modificat!', category='alert-success')
            return redirect(url_for('users.list_users'))
        except Exception as err:
            print err
            flash('Modificarile nu pot fi salvate!', category='alert-danger')

    form = user.fill_form()

    return render_template('users/edit.html', pagetitle='Detalii utilizator', form=form)


@mod.route('/utilizatori/sterge/<userid>')
@login_required
def delete_user(userid):
    """
    Used to delete an existing user
    """
    
    user = Users.get({"_id":userid})
    user.delete()

    return redirect(request.referrer)


@mod.route('/utilizatori/dezactiveaza/<userid>')
@login_required
def deactivate_user(userid):
    """
    Used to deactivate a user
    """
    
    user = Users.get({"_id":userid})
    user.update({"$set":{user.active.dbfield:False}})
    
    return redirect(request.referrer)


@mod.route('/utilizatori/activeaza/<userid>')
@login_required
def activate_user(userid):
    """
    Used to activate an existing user
    """
    
    user = Users.get({"_id":userid})
    user.update({"$set":{user.active.dbfield:True}})
    
    return redirect(request.referrer)


@mod.route("/utilizatori/ajax/lista", methods=['POST'])
@login_required
def get_results():
    """
    Used through AJAX to get datatables results
    """
    results = Users.to_datatables(request.form)

    for item in results["data"]:
        
        temp = item["username"]
        item["username"] = """<a href="{0}">{1}</a>""".format(url_for('users.edit_user',userid=item["DT_RowId"]),temp)

        action_column = ""
        
        if item["active"] and str(current_user._id.value) != item["actiuni"]:
            action_column+="""<span>
                     <a href="{0}" class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-user" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Dezactiveaza utilizator"></span></a>
                  </span>
                  """.format(url_for('users.deactivate_user',userid=item["DT_RowId"]))
        elif not item["active"] and str(current_user._id.value) != item["actiuni"]:
            action_column+="""<span>
                     <a href="{0}" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-user" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Activeaza utilizator"></span></a>
                  </span>""".format(url_for('users.activate_user',userid=item["DT_RowId"]))
        if str(current_user._id.value) != item["actiuni"]:
            action_column+="""<span>
                     <a href="javascript:void(0)" onclick="DeletePage('{0}')" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Sterge utilizator"></span></a>
                  </span>""".format(url_for("users.delete_user",userid=item["DT_RowId"]))

        item["actiuni"] = action_column

    return jsonify(results)

panoptes/webapp/templates/base.html
{% import "macros.html" as macros %}
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="/static/css/lumen-bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/datepicker.css" rel="stylesheet" media="screen">
    <!-- Custom styles for this template -->
    <link href="/static/css/app.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
  
    {% block body -%}

    {% block navbar %}
    {{ macros.mainnavmenu(session['menu'], current_user) }}
    {%- endblock navbar %}
    
    <div class="container">
    {{ macros.flashing() }}
    {% block content -%}
    {%- endblock content %}
    </div>

    {% block scripts %}
    <!-- <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script> -->
    <script type="text/javascript" src="/static/js/third.party/jquery-1.7.1.min.js"></script>
    
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/bootstrap-datepicker.js"></script>
    
    <script>
     $(document).ready(function() {
          window.setTimeout(function() {
        $(".alert").fadeTo(1500, 0).slideUp(100, function(){
            $(this).remove() 
        })}, 3000)});

         $('[data-toggle="tooltip"]').tooltip({
                container:'body'
            });
    </script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

panoptes/webapp/templates/home.html
{% extends "base.html" %}

{% block title %}{{pagetitle}}{% endblock %}

{% block content %}
<div class="panel panel-success">
    <div class="panel-heading" style="padding-top: 16px;">
        <h2 class="panel-title pull-left" style="font-size: 32px;">{{pagetitle}}</h2>
        
    </div>
    <div class="panel-body">
        <div class="col-md-6">
        <h3>Ultimii utilizatori activi:</h3>
        <ul>
        {% for item in last_users %}
            <li><h4>{{item.username}}</h4>
            Activ ultima data {{moment(item.last_seen,local=true).fromNow()}}</li>
        {% endfor %}
        </ul>
        </div>
        <div class="col-md-6">
        <h3>Ultimele pagini modificate:</h3>
        <ul>
        {% for item in last_pages %}
            <li><h4>{{item.title}}</h4>
            Modificata ultima data {{moment(item.last_mod,local=true).fromNow()}}</li>
        {% endfor %}
        </ul>
        </div>

        
    </div>
</div>
{% endblock %}

panoptes/webapp/templates/macros.html
{% macro flashing() %}

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
        <div class="alert {{ category }}">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Inchide</span>
            </button>
            <p>{{ message }}</p>
        </div>
      {% endfor %}
      {% endif %}
    {% endwith %}
    
{% endmacro %}

{% macro mainnavmenu(menuinfo, current_user) %}
  
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">StreamingMail Monitor</a>
        </div>
        {% if current_user.is_authenticated %}
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% for href,pgid,caption,dropdowns in menuinfo %}
            {% if dropdowns %}
            <li class="dropdown {% if session['activemenu'] == pgid %}active{% endif %}">
              <a class="dropdown-toggle disabled" data-toggle="dropdown" href="{{url_for(href)}}">{{caption}}<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
              {% for item in dropdowns %}
              <li><a href="{{item[0]}}">{{item[2]}}</a></li>
              {% endfor %}
              </ul>
            </li>
            {% else %}
            <li {% if session['activemenu'] == pgid %}class="active"{% endif %}><a href="{{url_for(href)}}">{{caption}}</a></li>
            {% endif %}
            {% endfor %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.permissions.value == 3 %}
            <li {% if session['activemenu'] == 'utilizatori' %}class="active"{% endif %}><a href="{{url_for('users.list_users')}}"> Utilizatori</a></li>
            {% endif %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{current_user.username.value}} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{url_for('users.changepswd', next=request.url)}}">Modifica parola</a></li>
                <li class="divider"></li>
                <li><a href="{{url_for('users.logout')}}">Log out</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
        {% endif %}
      </div>
    </nav>

{% endmacro %}

panoptes/webapp/templates/wtf-static.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{% else -%}
  <div class="form-group">
       {% if form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          <p class="form-control-static"> {{field.data|safe}}</p>
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types: "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="horizontal",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="") %}
<form  class="form form-horizontal
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
  ">
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

panoptes/webapp/templates/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'))}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-error{% endif %}">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {{field(class="form-control", **kwargs)|safe}}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {{field(class="form-control", **kwargs)|safe}}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="help-block">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="") %}
<form
  {%- if action %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if enctype %} enctype="{{enctype}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}