panoptes/webapp/users/models.py
# system imports
import datetime, string, random
# framework imports
from werkzeug import generate_password_hash, check_password_hash
from flask import current_app
from flask.ext.login import UserMixin, current_user
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
# app imports
from .. import mongo, login_manager
from ..core import BaseDocument
from ..core.viewhelpers import DataTableHelper
from forms import UserForm
from ..config import Config


class Users(UserMixin,BaseDocument,DataTableHelper):
    """
    Model for all the users in the app
    """
    fromdict = {
                "username" : {"dbfield":"un", "required":True, "verbose":"Nume utilizator"},
                "email" : {"dbfield":"em", "required":True, "unique":True, "verbose":"Email"},
                "pswd" : {"dbfield":"pw", "required": True},
                "permissions" : {"dbfield":"pm", "required":True, "verbose":"Permisiuni"},
                "last_seen" : {"dbfield":"ls", "verbose":"Ultima vizita", "default":datetime.datetime.now},
                "active" : {"dbfield":"at", "verbose":"Activ", "default":True, "validate":bool}
                }

    db = mongo.db
    collection = "users"
    show_fields = ["username","email","active","last_seen"]
    button_field = True
    
    def __init__(self, **kwargs):
       BaseDocument.__init__(self,**kwargs)


    @property
    def password(self):
        raise AttributeError('Parola nu poate fi accesata direct')


    @password.setter
    def password(self,passwd):
        self.pswd.value = generate_password_hash(passwd)


    def random_password(self):
        """
        Used to generate a random password for new users
        """
        temp_pass = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(6))
        self.password = temp_pass
        return temp_pass


    def verify_password(self,passwd):
        return check_password_hash(self.pswd.value,passwd)


    def generate_reset_token(self, expiration=7200):
        """
        Used to generate a password reset token for a user account
        """
        s = Serializer(current_app.config['SECRET_KEY'],expiration)
        return s.dumps({'reset': unicode(self.id)})


    def resetpass(self,token):
        """
        Used to check for the reset password token for a user account
        """
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return None
        if data.get('reset') != unicode(self._id.value):
            return None
        return self._id.value


    def ping(self):
        self.last_seen.value = datetime.datetime.now()


    def is_active(self):
        return self.active.value


    def get_id(self):
        return self._id.value


    def messages(self):
        pass


    def is_admin(self):
        return self.permissions.value == config.PERMISSIONS['admin']


    def is_manager(self):
        return self.permissions.value == config.PERMISSIONS['manager']


    @classmethod
    def get_form(cls):

        return UserForm()


@login_manager.user_loader
def load_user(user_id):
    try:
        user = Users.get({"_id":user_id})
        return user
    except:
        return None

panoptes/webapp/users/forms.py
# framework imports
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, ValidationError
from wtforms.validators import Required, EqualTo
from ..config import Config


class UserForm(Form):

    username = StringField(label='Nume utilizator')
    email = StringField(label='Email utilizator', validators=[Required('Campul trebuie completat!')])
    permissions = SelectField(label='Permisiuni utilizator', choices=[(Config.PERMISSIONS[x],x) for x in Config.PERMISSIONS], coerce=int)
    submit = SubmitField('Salveaza')
        
    def validate_email(self,field):
        try:
            user = Users.get({"email":field.data})
            if user:
                raise ValidationError('Email este deja folosit!')
        except:
            pass


class LoginForm(Form):

    email = StringField(label='Adresa de email', validators=[Required('Campul trebuie completat!')])
    password = PasswordField(label='Parola', validators=[Required('Campul trebuie completat!')])
    remember_me = BooleanField(label='Tine-ma minte')
    submit = SubmitField('Login')


class ResetPassForm(Form):

    email = StringField(label='Email utilizator', validators=[Required('Campul trebuie completat!')])
    submit = SubmitField('Trimite')


class NewPassForm(Form):

    password = PasswordField(label='Parola noua', validators=[Required('Campul trebuie completat!')])
    pass2 = PasswordField(label='Repeta parola', validators=[Required('Campul trebuie completat!'), EqualTo('password')])
    submit = SubmitField('Salveaza')


class ChangePassForm(Form):

    oldpass = PasswordField(label='Parola veche', validators=[Required()])
    newpass = PasswordField(label='Parola noua', validators=[Required()])
    checknewpass = PasswordField(label='Parola noua', validators=[Required(),EqualTo('newpass')])
    submit = SubmitField('Salveaza')

panoptes/webapp/users/__init__.py
# system imports
from functools import wraps
# framework imports
from flask import flash, redirect, request
from flask.ext.login import current_user,login_required


def manager_required(f):
    @login_required
    @wraps(f)
    def decorated_function(*args,**kwargs):
        if not (current_user.is_manager() or current_user.is_admin()):
            flash('Nu puteti face aceasta operatie!', category='alert-danger')
            return redirect(request.referrer)
      
        return f(*args,**kwargs)

    return decorated_function

panoptes/webapp/users/views.py
# system imports
import datetime
# framework imports
from flask import Blueprint, request, render_template, flash, redirect, url_for, session, current_app, jsonify
from flask.ext.login import login_user, logout_user, login_required, current_user
# app imports
from models import Users
from forms import UserForm, LoginForm, ResetPassForm, NewPassForm, ChangePassForm
from ..utils.mail import send_email


mod = Blueprint('users',__name__)


@mod.before_request
def before_request():
    session['menu'] = current_app.config['MENU']
    session['activemenu'] = 'utilizatori'


@mod.route('/login', methods=['GET','POST'])
def login():
    """
    Generates and handles the login for the user
    """
    form = LoginForm()

    if form.validate_on_submit():
        try:
            user = Users.get({"email":form.email.data})
            if not user.active.value:
                flash('Contul tau a expirat! Te rugam contacteaza-ne!', category='alert-danger')
                return redirect(request.referrer)
            if user.verify_password(form.password.data):
                login_user(user,form.remember_me.data)
                user.ping()
                return redirect('/')
            else:
                raise Exception('Not authorised',form.email.data)

        except Exception as err:
            print err
            flash('Parola sau adresa de email este invalida!', category='alert-danger')

    return render_template('users/login.html', pagetitle='Login',form=form,login=True, current_user=current_user)


@mod.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect('/')


@mod.route('/reseteazaparola/', methods=['GET','POST'])
def resetlink():
    """
    Generates and handles the password reset page
    """

    form = ResetPassForm()

    if form.validate_on_submit():
        try:
            user = Users.get({"email":form.email.data})
            token = user.generate_reset_token()
            send_email(user.email,'Resetare parola','users/email/passwdreset',user=user,token=token)
            flash('Parola a fost resetata! Va rugam urmati instructiunile primite pe email!',category='alert-success')
            return redirect(request.referrer)

        except Exception as err:
            flash('Adresa de email gresita!',category='alert-danger')
            return redirect(request.referrer)

    return render_template('users/login.html',pagetitle='Resetare parola',form=form,login=False)


@mod.route('/reseteaza/<email>/<token>', methods=['GET','POST'])
def resetpassword(email,token):
    """
    Handles the password reset for a given email and token
    """

    form = NewPassForm()

    if form.validate_on_submit():
        try:
            user = Users.get({"email":email})
            if user.resetpass(token):
                user.password = form.password.data
                user.save()
                flash('Parola schimbata!',category='alert-success')
                return redirect(url_for('users.login'))
                
            else:
                raise Exception

        except:
            flash('Token invalid!',category='alert-danger')
            return redirect(url_for('users.resetlink'))

    return render_template('users/login.html',pagetitle='Resetare parola',form=form,login=False)


@mod.route('/schimbaparola', methods=['GET','POST'])
@login_required
def changepswd():
    """
    Handles the change of password for the current user
    """

    form = ChangePassForm()

    if form.validate_on_submit():
        try:
            user = current_user
            print "here"
            if user.verify_password(form.oldpass.data):
                print "pass ok"
                user.password = form.newpass.data
                print user.username.value
                print form.newpass.data
                user.save()
                flash('Parola schimbata!',category='alert-success')
                return redirect(request.args.get('next') or '/home/')
            else:
                raise Exception('Not authorised',form.email.data)

        except Exception as err:
            print err
            flash('Modificarea nu poate fi facuta!', category='alert-danger')

    return render_template('users/edit.html', pagetitle='Schimba parola', form=form)


@mod.route('/home')
@login_required
def home():
    """
    Generates the homepage for the logged in user
    """

    return redirect(url_for('users.list_users'))


@mod.route('/utilizatori/lista')
@login_required
def list_users():
    """
    Generates a list of all users
    """
    return render_template('users/list.html', pagetitle='Lista Utilizatori', results=url_for('users.get_results'), table_head=Users.table_head(), columns=Users.datatables_columns())


@mod.route('/utilizatori/adauga', methods=['GET','POST'])
@login_required
def add_user():
    """
    Used to add a new user to the admin
    """

    form = UserForm()

    if form.validate_on_submit():
        try:
            user = Users()
            user.populate_from_form(form)
            send_email(user.email.value,'Resetare parola','users/email/sendpass',user=user,psw=user.random_password())
            user.save()
            flash('Utilizatorul adaugat!', category='alert-success')
            return redirect(url_for('users.list_users'))
        except Exception as err:
            flash('Utilizatorul nu poate fi adaugat!', category='alert-danger')

    return render_template('users/add.html', pagetitle='Adauga utilizator', form=form)


@mod.route('/utilizatori/modifica/<userid>', methods=['GET','POST'])
@login_required
def edit_user(userid):
    """
    Used to edit an existing user
    """
    
    user = Users.get({"_id":userid})
    form = UserForm()

    if form.validate_on_submit():
        try:
            user.populate_from_form(form)
            user.save()
            flash('Utilizatorul modificat!', category='alert-success')
            return redirect(url_for('users.list_users'))
        except Exception as err:
            print err
            flash('Modificarile nu pot fi salvate!', category='alert-danger')

    form = user.fill_form()

    return render_template('users/edit.html', pagetitle='Detalii utilizator', form=form)


@mod.route('/utilizatori/sterge/<userid>')
@login_required
def delete_user(userid):
    """
    Used to delete an existing user
    """
    
    user = Users.get({"_id":userid})
    user.delete()

    return redirect(request.referrer)


@mod.route('/utilizatori/dezactiveaza/<userid>')
@login_required
def deactivate_user(userid):
    """
    Used to deactivate a user
    """
    
    user = Users.get({"_id":userid})
    user.update({"$set":{user.active.dbfield:False}})
    
    return redirect(request.referrer)


@mod.route('/utilizatori/activeaza/<userid>')
@login_required
def activate_user(userid):
    """
    Used to activate an existing user
    """
    
    user = Users.get({"_id":userid})
    user.update({"$set":{user.active.dbfield:True}})
    
    return redirect(request.referrer)


@mod.route("/utilizatori/ajax/lista", methods=['POST'])
@login_required
def get_results():
    """
    Used through AJAX to get datatables results
    """
    results = Users.to_datatables(request.form)

    for item in results["data"]:
        
        temp = item["username"]
        item["username"] = """<a href="{0}">{1}</a>""".format(url_for('users.edit_user',userid=item["DT_RowId"]),temp)

        action_column = ""
        
        if item["active"] and str(current_user._id.value) != item["actiuni"]:
            action_column+="""<span>
                     <a href="{0}" class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-user" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Dezactiveaza utilizator"></span></a>
                  </span>
                  """.format(url_for('users.deactivate_user',userid=item["DT_RowId"]))
        elif not item["active"] and str(current_user._id.value) != item["actiuni"]:
            action_column+="""<span>
                     <a href="{0}" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-user" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Activeaza utilizator"></span></a>
                  </span>""".format(url_for('users.activate_user',userid=item["DT_RowId"]))
        if str(current_user._id.value) != item["actiuni"]:
            action_column+="""<span>
                     <a href="javascript:void(0)" onclick="DeletePage('{0}')" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Sterge utilizator"></span></a>
                  </span>""".format(url_for("users.delete_user",userid=item["DT_RowId"]))

        item["actiuni"] = action_column

    return jsonify(results)

panoptes/webapp/templates/users/add.html
{% extends "/base.html" %}
{% import "/wtf.html" as wtf %}


{% block title %}{{pagetitle}}{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading" style="padding-top: 16px;">
        <h2 class="panel-title pull-left" style="font-size: 32px;">{{pagetitle}}</h2>
        <span class="pull-right" style="margin-right: 15px;">
            <a href="{{request.referrer}}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Anuleaza</a>
        </span>
    </div>
    <div class="panel-body">
        {{ wtf.quick_form(form=form, form_type="horizontal", horizontal_columns=("md",4,4), button_map={'submit':'success'}) }}
    </div>
</div>
{% endblock %}

panoptes/webapp/templates/users/edit.html
{% extends "/base.html" %}
{% import "/wtf.html" as wtf %}


{% block title %}{{pagetitle}}{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading" style="padding-top: 16px;">
        <h2 class="panel-title pull-left" style="font-size: 32px;">{{pagetitle}}</h2>
        <span class="pull-right" style="margin-right: 15px;">
            <a href="{{request.referrer}}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Anuleaza</a>
        </span>
    </div>
    <div class="panel-body">
        {{ wtf.quick_form(form=form, form_type="horizontal", horizontal_columns=("md",4,4), button_map={'submit':'success'}) }}
    </div>
</div>
{% endblock %}

panoptes/webapp/templates/users/list.html
{% extends "/base.html" %}

{%- block styles %}
{{super()}}
<link href="/static/css/dataTables.bootstrap.min.css" rel="stylesheet" media="screen">
<link href="/static/css/datatables.min.css" rel="stylesheet" media="screen">
{%- endblock styles %}

{% block title %}{{pagetitle}}{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading" style="padding-top: 16px;">
        <h2 class="panel-title pull-left" style="font-size: 32px;">{{pagetitle}}</h2>
        <div class="btn-group pull-right">  
    </div>
    <span class="pull-right" style="margin-right: 15px;">
            <a href="{{url_for('users.add_user')}}" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Adauga utilizator</a>
        </span>
    </div>
    <div class="panel-body">
        <table id="maintable" class="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    {% for t in table_head %}
                    <th>{{t}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        
    </div>
</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script type="text/javascript" src="/static/js/datatables.min.js"></script>
<script type="text/javascript" src="/static/js/dataTables.bootstrap.min.js"></script>
<script type="text/javascript">

function DeletePage(url) {

  if (confirm("Esti sigur ca vrei sa stergi utilizatorul? Stergerea este definitiva!")) {
    window.open(url,"_self")
  }
}

$(document).ready(function() {
    $('#maintable').DataTable( {
        "processing": true,
        "serverSide": true,
        "stateSave": true,
        "ajax": {
            "url": '{{results}}',
            "type": 'POST'
        },
        "columns" : [
            {"data":"username"},
            {"data":"email"},
            {"data":"active"},
            {"data":"last_seen"},
            {"data":"actiuni"}
                ]
    } );
} );

</script>
{% endblock %}

panoptes/webapp/templates/users/login.html
{% extends "/base.html" %}
{% import "/wtf.html" as wtf %}


{% block title %}Login{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <div class="login-block">
        {{ wtf.quick_form(form, form_type="horizontal",horizontal_columns=("lg",3,6),button_map={'submit':'success'}) }}

        {% if login %}
        <p><a href="{{url_for('users.resetlink')}}">Am uitat parola!</a></p>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}