panoptes/webapp/services/models.py
# system imports
import datetime, string, random
# framework imports
from flask import current_app
# app imports
from .. import mongo
from ..core import BaseDocument
from ..core.viewhelpers import DataTableHelper
from forms import ServiceForm


class Services(BaseDocument,DataTableHelper):
    """
    Model for all the services that need to be monitored by the app
    """
    fromdict = {
                "server" : {"dbfield":"ip", "required":True, "verbose":"IP server"},
                "port" : {"dbfield":"po", "required":True, "verbose":"Port server"},
                "service_type" : {"dbfield":"st", "required": True, "verbose":"Tip serviciu"},
                "last_check" : {"dbfield":"ls", "verbose":"Ultima verificare"},
                "active" : {"dbfield":"at", "verbose":"Activ", "default":True, "validate":bool},
                "authentication" : {"dbfield":"au", "verbose":"Autentificare"}
                }

    db = mongo.db
    collection = "services"
    show_fields = ["server","port","service_type","last_check","active"]
    button_field = True
    
    def __init__(self, **kwargs):
        BaseDocument.__init__(self,**kwargs)


    @classmethod
    def get_active(cls,group_by_type=True):

        raw_results = [x for x in cls.connection().find({"at":True})]
        if group_by_type:
            groups = set([x['st'] for x in raw_results])
            results = {x:[] for x in groups}
            for item in raw_results:
                results[item["st"]].append(cls(values=item))

        else:
            results = {"ungrouped":[cls(values=item) for item in raw_results]}

        return results


    def get_form(self):

        return ServiceForm()

panoptes/webapp/services/forms.py
# framework imports
from flask.ext.wtf import Form
from wtforms import StringField, BooleanField, SubmitField, SelectField, ValidationError
from wtforms.validators import Required, EqualTo
#app imports
from ..config import Config


class ServiceForm(Form):

    server = StringField(label="IP server", validators=[Required('Campul trebuie completat!')])
    port = StringField(label="Port server", validators=[Required('Campul trebuie completat!')])
    service_type = SelectField(label="Tip serviciu", choices=[(x,x.upper()) for x in Config.SERVICE_TYPES])
    authentication = SelectField(label="Autentificare", choices=[(False,'NU'),(True,'DA')], coerce=bool)
    submit = SubmitField('Salveaza')

panoptes/webapp/services/plugins/__init__.py
from mongo import mongo_get_panel_results, mongo_get_datatable_results
from otherdb import redis_get_panel_results, redis_get_datatable_results


REGISTERED_SERVICES = {
    "mongo":{"panel":mongo_get_panel_results,
             "datatable":mongo_get_datatable_results},
    "redis":{"panel":redis_get_panel_results,
             "datatable":redis_get_datatable_results}
}

panoptes/webapp/services/views.py
# system imports
import datetime
# framework imports
from flask import Blueprint, request, render_template, flash, redirect, url_for, session, current_app, jsonify
from flask.ext.login import login_required, current_user
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
# app imports
from ..users import manager_required
from models import Services
from forms import ServiceForm
from plugins import REGISTERED_SERVICES


mod = Blueprint('services',__name__)


@mod.before_request
def before_request():
    session['menu'] = current_app.config['MENU']
    session['activemenu'] = 'services'


@mod.route('/setari/lista')
@manager_required
@login_required
def list_services():
    """
    Generates a list of all the registered services that can be checked
    """
    return render_template('services/settings/list_services.html', pagetitle='Lista servicii', results=url_for('services.get_results'), table_head=Services.table_head(), columns=Services.datatables_columns())


@mod.route('/setari/adauga', methods=['GET','POST'])
@manager_required
@login_required
def add_service():
    """
    Used to register a new service
    """

    form = ServiceForm()

    if form.validate_on_submit():
        try:
            srv = Services()
            srv.populate_from_form(form)
            srv.authentication.value = {"db":request.form.get('authdb'),"user":request.form.get('authuser'),"pswd":request.form.get("authpass")}
            srv.save()
            flash('Datele au fost adaugate!', category='alert-success')
            return redirect(url_for('services.list_services'))
        except Exception as err:
            flash('Datele nu pot fi adaugate!', category='alert-danger')

    return render_template('services/settings/add.html', pagetitle='Adauga serviciu', form=form)


@mod.route('/setari/modifica/<srvid>', methods=['GET','POST'])
@manager_required
@login_required
def edit_service(srvid):
    """
    Used to edit a registered service
    """
    class F(ServiceForm):
        pass
    
    srv = Services.get({"_id":srvid})
    form = ServiceForm()

    if form.validate_on_submit():
        try:
            srv.populate_from_form(form)
            print request.form
            srv.authentication.value = {"db":request.form.get('authdb'),"user":request.form.get('authuser'),"pswd":request.form.get("authpass")}
            srv.save()
            flash('Datele au fost modificate!', category='alert-success')
            return redirect(url_for('services.list_services'))
        except Exception as err:
            flash('Modificarile nu pot fi salvate!', category='alert-danger')


    if srv.authentication.value:
        if srv.authentication.value['db']:
            F.authdb = StringField(label="Db autentificare")
        if srv.authentication.value['user']:
            F.authuser = StringField(label="User")
        F.authpass = StringField(label="Parola")
        F.submit = SubmitField('Salveaza')
        
    form = srv.fill_form(_form=F())
    del form.authentication
    if srv.authentication.value:
        if srv.authentication.value['db']:
            form.authdb.data = srv.authentication.value['db']
        if srv.authentication.value['user']:
            form.authuser.data = srv.authentication.value['user']
        form.authpass.data = srv.authentication.value['pswd']
        

    return render_template('services/settings/edit.html', pagetitle='Detalii serviciu', form=form)


@mod.route('/setari/sterge/<srvid>')
@manager_required
@login_required
def delete_service(srvid):
    """
    Used to delete an existing service
    """
    
    srv = Services.get({"_id":srvid})
    srv.delete()

    return redirect(request.referrer)


@mod.route('/setari/dezactiveaza/<srvid>')
@manager_required
@login_required
def deactivate_service(srvid):
    """
    Used through AJAX to deactivate a service
    """
    
    srv = Services.get({"_id":srvid})
    srv.update({"$set":{srv.active.dbfield:False}})
    
    return redirect(request.referrer)


@mod.route('/setari/activeaza/<srvid>')
@manager_required
@login_required
def activate_service(srvid):
    """
    Used through AJAX to activate an existing service
    """
    
    srv = Services.get({"_id":srvid})
    srv.update({"$set":{srv.active.dbfield:True}})
    
    return redirect(request.referrer)


@mod.route("/setari/ajax/lista", methods=['POST'])
@manager_required
@login_required
def get_results():
    """
    Used through AJAX to get datatables results
    """
    
    results = Services.to_datatables(request.form)

    for item in results["data"]:
        
        temp = item["server"]
        item["server"] = """<a href="{0}">{1}</a>""".format(url_for('services.edit_service',srvid=item["DT_RowId"]),temp)

        action_column = ""
        
        if item["active"]:
            action_column+="""<span>
                     <a href="{0}" class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-eye-close" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Dezactiveaza serviciu"></span></a>
                  </span>
                  """.format(url_for('services.deactivate_service',srvid=item["DT_RowId"]))
        else:
            action_column+="""<span>
                     <a href="{0}" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-eye-open" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Activeaza serviciu"></span></a>
                  </span>""".format(url_for('services.activate_service',srvid=item["DT_RowId"]))
        action_column+="""<span>
                     <a href="javascript:void(0)" onclick="DeletePage('{0}')" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Sterge serviciu"></span></a>
                  </span>""".format(url_for("services.delete_service",srvid=item["DT_RowId"]))
                  
        item["actiuni"] = action_column

    return jsonify(results)


@mod.route('/db/home')
@login_required
def home():
    """
    Generates the homepage for the software services section
    """
    table_head = ["Server","Serviciu","Uptime","Observatii"]

    return render_template('services/list.html', pagetitle='Sumarizare statusuri db', results=url_for('services.get_datatables_results',_filter='0'),table_head=table_head)


@mod.route('/db/<db_type>')
@login_required
def dbstatus(db_type=None):
    """
    Generates a stats page for each service type
    """
    live_services = Services.get_active()
    results = REGISTERED_SERVICES[db_type]["panel"](live_services.get(db_type))

    template = 'services/detailed_%s.html' % db_type

    return render_template(template, pagetitle='Statusuri db pentru '+str(db_type).upper(), results=results)


@mod.route('/db/ajax/lista/<_filter>', methods=["POST"])
@login_required
def get_datatables_results(_filter=None):

    live_services = Services.get_active()

    stats = []
    stats_redis = REGISTERED_SERVICES['redis']["datatable"](live_services.get('redis'))
    stats_mongo = REGISTERED_SERVICES['mongo']["datatable"](live_services.get('mongo'))

    if _filter == 'mongo' and stats_mongo:
        stats = stats_mongo['data']
    elif _filter == 'redis' and stats_redis:
        stats = stats_redis['data']
    else:
        stats.extend(stats_mongo['data'])
        stats.extend(stats_redis['data'])

    output = {}
    output['draw'] = request.form['draw']
    output['data'] = stats
    output['recordsTotal'] = len(stats)
    output['recordsFiltered'] = len(stats)

    return jsonify(output)

panoptes/webapp/templates/services/settings/add.html
{% extends "/base.html" %}
{% import "/wtf.html" as wtf %}


{% block title %}{{pagetitle}}{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading" style="padding-top: 16px;">
        <h2 class="panel-title pull-left" style="font-size: 32px;">{{pagetitle}}</h2>
        <span class="pull-right" style="margin-right: 15px;">
            <a href="{{request.referrer}}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Anuleaza</a>
        </span>
    </div>
    <div class="panel-body">
        {{ wtf.quick_form(form=form, form_type="horizontal", horizontal_columns=("md",4,4), button_map={'submit':'success'}) }}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script type="text/javascript">

$(document).ready(function() {
	$("#authentication").on('change', function() {
		var authdb = '<div class="form-group tempauth"> \
		        <label class="control-label  col-md-4" for="authdb">Db autentificare</label> \
		        <div class=" col-md-4"> \
		          <input class="form-control" id="authdb" name="authdb" required type="text" value=""> \
		        </div> \
		</div>';
		var authuser = '<div class="form-group tempauth"> \
		        <label class="control-label  col-md-4" for="authuser">User</label> \
		        <div class=" col-md-4"> \
		          <input class="form-control" id="authuser" name="authuser" required type="text" value=""> \
		        </div> \
		</div>';
		var authpass = '<div class="form-group tempauth"> \
		        <label class="control-label  col-md-4" for="authpass">Parola</label> \
		        <div class=" col-md-4"> \
		          <input class="form-control" id="authpass" name="authpass" required type="text" value=""> \
		        </div> \
		</div>';
		var choice = $(this).find("option:selected").text();
		var db = $("#service_type").find("option:selected").text();
		if (choice === 'DA' && db === 'MONGO') {
			$(this).closest(".form-group").after(authdb+authuser+authpass);
		}
		else if (choice === 'DA' && db === 'REDIS') {
			$(this).closest(".form-group").after(authpass);
		}
		else if (choice === 'NU') {
			$(this).closest(".form-group").nextAll(".tempauth").remove();
		};
	});
	$("#service_type").on('change', function() {
		$(this).closest(".form-group").nextAll(".tempauth").remove();
		$("#authentication").val('NU')
	});


} );

</script>
{% endblock %}

panoptes/webapp/templates/services/settings/edit.html
{% extends "/base.html" %}
{% import "/wtf.html" as wtf %}


{% block title %}{{pagetitle}}{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading" style="padding-top: 16px;">
        <h2 class="panel-title pull-left" style="font-size: 32px;">{{pagetitle}}</h2>
        <span class="pull-right" style="margin-right: 15px;">
            <a href="{{request.referrer}}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Anuleaza</a>
        </span>
    </div>
    <div class="panel-body">
        {{ wtf.quick_form(form=form, form_type="horizontal", horizontal_columns=("md",4,4), button_map={'submit':'success'}) }}
    </div>
</div>
{% endblock %}

panoptes/webapp/templates/services/settings/list_services.html
{% extends "/base.html" %}

{%- block styles %}
{{super()}}
<link href="/static/css/dataTables.bootstrap.min.css" rel="stylesheet" media="screen">
<link href="/static/css/datatables.min.css" rel="stylesheet" media="screen">
{%- endblock styles %}

{% block title %}{{pagetitle}}{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading" style="padding-top: 16px;">
        <h2 class="panel-title pull-left" style="font-size: 32px;">{{pagetitle}}</h2>
        <div class="btn-group pull-right">  
    </div>
    <span class="pull-right" style="margin-right: 15px;">
            <a href="{{url_for('services.add_service')}}" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Adauga serviciu</a>
        </span>
    </div>
    <div class="panel-body">
        <table id="maintable" class="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    {% for t in table_head %}
                    <th>{{t}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        
    </div>
</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script type="text/javascript" src="/static/js/datatables.min.js"></script>
<script type="text/javascript" src="/static/js/dataTables.bootstrap.min.js"></script>
<script type="text/javascript">

function DeletePage(url) {

  if (confirm("Esti sigur ca vrei sa stergi serviciul? Stergerea este definitiva!")) {
    window.open(url,"_self")
  }
}

$(document).ready(function() {
    $('#maintable').DataTable( {
        "processing": true,
        "serverSide": true,
        "stateSave": true,
        "ajax": {
            "url": '{{results}}',
            "type": 'POST'
        },
        "columns" : [
            {"data":"server"},
            {"data":"port"},
            {"data":"service_type"},
            {"data":"last_check"},
            {"data":"active"},
            {"data":"actiuni"}
                ]
    } );
} );

</script>
{% endblock %}